#!/bin/bash
echo 'update binary FTE to /usr/local/bin and ./extra/' 
cp src/nfte /usr/local/bin/nfte
cp src/cfte /usr/local/bin/cfte
cp src/vfte /usr/local/bin/vfte
cp src/xfte /usr/local/bin/xfte
cp src/sfte /usr/local/bin/sfte

cp src/nfte extra/nfte
cp src/cfte extra/cfte
cp src/vfte extra/vfte
cp src/xfte extra/xfte
cp src/sfte extra/sfte

