#
#
#
#
# 
myFTE=$(HOME)



all:
	@echo ' '
	@echo '    ins -- install fte2006'
	@echo '    rc  -- compiler .fterc for U'
	@echo 'What command for fte install. ( ins, rc )?'
	
ins:
	cp -f fte cfte nfte xfte /usr/local/bin
	cp -f vgrep /usr/local/bin
	
rc:	
	sh cfgrc
	
	
	